# Generated by Django 5.0.1 on 2024-01-19 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('recording', models.FileField(upload_to='recording/')),
                ('source', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(verbose_name='Index in lecture')),
                ('listen_again', models.FileField(blank=True, null=True, upload_to='recording/')),
                ('question', models.TextField()),
                ('choice_a', models.TextField(blank=True)),
                ('choice_b', models.TextField(blank=True)),
                ('choice_c', models.TextField(blank=True)),
                ('choice_d', models.TextField(blank=True)),
                ('choice_e', models.TextField(blank=True)),
                ('choice_f', models.TextField(blank=True)),
                ('answer', models.CharField(blank=True, max_length=6)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(blank=True, max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.listeningquestion')),
            ],
        ),
    ]
