# Generated by Django 5.0.1 on 2024-01-19 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listening', '0001_initial'),
        ('reading', '0001_initial'),
        ('speaking', '0001_initial'),
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(max_length=200)),
                ('listening_list', models.ManyToManyField(blank=True, to='listening.lecture')),
                ('reading_list', models.ManyToManyField(blank=True, to='reading.passage')),
                ('speaking_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speaking.independentsp')),
                ('speaking_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IntegratedSp_Q2', to='speaking.integratedsp')),
                ('speaking_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IntegratedSp_Q3', to='speaking.integratedsp')),
                ('speaking_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IntegratedSp_Q4', to='speaking.integratedsp')),
                ('writing_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writing.integratedwt')),
                ('writing_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='writing.acdiscussion')),
            ],
        ),
    ]
