# Generated by Django 5.0.1 on 2024-01-19 08:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentSp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IntegratedSp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('passage', ckeditor.fields.RichTextField(blank=True)),
                ('conversation', models.FileField(upload_to='speaking_conv/')),
            ],
        ),
    ]
